language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 5.6
 - 7.0

env:
  - MOODLE_BRANCH=MOODLE_33_STABLE DB=mysqli IGNORE_PATHS=integration
  - MOODLE_BRANCH=MOODLE_32_STABLE DB=mysqli IGNORE_PATHS=integration
  - MOODLE_BRANCH=MOODLE_31_STABLE DB=mysqli IGNORE_PATHS=integration
  - MOODLE_BRANCH=MOODLE_30_STABLE DB=pgsql  IGNORE_PATHS=integration
  - MOODLE_BRANCH=MOODLE_29_STABLE DB=mysqli IGNORE_PATHS=integration
  - MOODLE_BRANCH=MOODLE_28_STABLE DB=pgsql  IGNORE_PATHS=integration
  - MOODLE_BRANCH=MOODLE_27_STABLE DB=mysqli IGNORE_PATHS=integration

matrix:
  exclude:
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_29_STABLE DB=mysqli IGNORE_PATHS=integration
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_28_STABLE DB=pgsql  IGNORE_PATHS=integration
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_27_STABLE DB=mysqli IGNORE_PATHS=integration
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_31_STABLE DB=mysqli IGNORE_PATHS=integration
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_30_STABLE DB=pgsql  IGNORE_PATHS=integration
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_29_STABLE DB=mysqli IGNORE_PATHS=integration
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_28_STABLE DB=pgsql  IGNORE_PATHS=integration
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_27_STABLE DB=mysqli IGNORE_PATHS=integration
    - php: 5.4
      env: MOODLE_BRANCH=MOODLE_32_STABLE DB=mysqli IGNORE_PATHS=integration
    - php: 5.4
      env: MOODLE_BRANCH=MOODLE_33_STABLE DB=mysqli IGNORE_PATHS=integration
  include:
    - php: 5.4
      env: MOODLE_BRANCH=MOODLE_31_STABLE DB=mysqli IGNORE_PATHS=integration
    - php: 5.4
      env: MOODLE_BRANCH=MOODLE_30_STABLE DB=pgsql  IGNORE_PATHS=integration
    - php: 5.4
      env: MOODLE_BRANCH=MOODLE_29_STABLE DB=mysqli IGNORE_PATHS=integration
    - php: 5.4
      env: MOODLE_BRANCH=MOODLE_28_STABLE DB=pgsql  IGNORE_PATHS=integration
    - php: 5.4
      env: MOODLE_BRANCH=MOODLE_27_STABLE DB=mysqli IGNORE_PATHS=integration

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install
script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci behat