notifications:
  email: false

language: php

sudo: required

addons:
  postgresql: "9.6"
  apt:
    packages:
      # - oracle-java8-installer
      # - oracle-java8-set-default
      - chromium-chromedriver

services:
  - postgresql

jobs:
    # Enable fast finish.
    # This will fail the build if a single job fails (except those in allow_failures).
    # It will not stop the jobs from running.
    fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  - 7.0
  # - 7.1
  # - 7.2
  # - 7.3
  - 7.4

env:
  global:
    - IGNORE_PATHS=classes/privacy,ignore,node_modules,integration,filtersettings.php,render
    # - IGNORE_NAMES=ignore_name.php
    # - MUSTACHE_IGNORE_NAMES=broken.mustache
    - PROFILE=chrome
    - COVERAGE=false
    - PHPUNIT_IGNORE_PATHS=classes/privacy,ignore,node_modules,integration,filtersettings.php,render
    - DB=pgsql

  matrix:
    - MOODLE_BRANCH=MOODLE_311_STABLE
    - MOODLE_BRANCH=MOODLE_310_STABLE
    - MOODLE_BRANCH=MOODLE_39_STABLE
    - MOODLE_BRANCH=MOODLE_38_STABLE
    - MOODLE_BRANCH=MOODLE_37_STABLE
    - MOODLE_BRANCH=MOODLE_35_STABLE

matrix:
  exclude:
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_310_STABLE
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_311_STABLE
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_310_STABLE
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_311_STABLE
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.4
      env: MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.4
      env: MOODLE_BRANCH=MOODLE_37_STABLE


before_install:
  - if [ "$NODEJS" = 14 ]; then
      nvm install 14.0.0;
      nvm use 14.0.0;
    else
      nvm install 8.9;
      nvm use 8.9;
    fi
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  # - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  # - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  - composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  # - docker run -d -p 127.0.0.1:4444:4444 --net=host -v /dev/shm:/dev/shm selenium/standalone-${PROFILE}:3

install:
  - moodle-plugin-ci add-plugin --branch $TRAVIS_BRANCH wiris/moodle-atto_wiris
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - if [ "$MOODLE_BRANCH" = MOODLE_35_STABLE ]; then
      moodle-plugin-ci grunt;
    else
      moodle-plugin-ci grunt -t eslint;
    fi
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat --profile $PROFILE